name: Build

on:
  push:
    tags:
      - '*'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug APK
        run: |
          bash ./gradlew assembleDebug --stacktrace
          ls app/build/outputs/apk/debug/

      - name: Upload APK
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/debug/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
